// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSHealthCare.Infrastructure;

#nullable disable

namespace SSHealthCare.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607051942_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSHealthCare.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfIncorporation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "JOb",
                            BusinessType = "JOb",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7410),
                            Email = "admin@shiwansh.com",
                            Logo = "jobportal.png",
                            Name = "SS Job Portal",
                            RegistrationNumber = "111A",
                            Website = "http://www.dotnetinfotech.com/"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Hospital",
                            BusinessType = "Hospital",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7430),
                            Email = "admin@shiwansh.com",
                            Logo = "healthcare.png",
                            Name = "SS Health Care",
                            RegistrationNumber = "222B",
                            Website = "http://www.dotnetinfotech.com/"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Hospital",
                            BusinessType = "Hospital",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7432),
                            Email = "admin@shiwansh.com",
                            Logo = "healthcare.png",
                            Name = "SS Health Care",
                            RegistrationNumber = "333C",
                            Website = "http://www.dotnetinfotech.com/"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Hospital",
                            BusinessType = "Hospital",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7435),
                            Email = "admin@shiwansh.com",
                            Logo = "healthcare.png",
                            Name = "SS Health Care",
                            RegistrationNumber = "444D",
                            Website = "http://www.dotnetinfotech.com/"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Job",
                            BusinessType = "Job",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7437),
                            Email = "admin@shiwansh.com",
                            Logo = "jobportal.png",
                            Name = "SS Job Portal",
                            RegistrationNumber = "555E",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Job",
                            BusinessType = "Job",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7440),
                            Email = "admin@shiwansh.com",
                            Logo = "jobportal.png",
                            Name = "SS Job Portal",
                            RegistrationNumber = "666F",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Job",
                            BusinessType = "Job",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7443),
                            Email = "admin@shiwansh.com",
                            Logo = "jobportal.png",
                            Name = "SS Job Portal",
                            RegistrationNumber = "777G",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Housing",
                            BusinessType = "Housing",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7445),
                            Email = "admin@shiwansh.com",
                            Logo = "ehousing.png",
                            Name = "SS E-Housing",
                            RegistrationNumber = "888H",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Housing",
                            BusinessType = "Housing",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7448),
                            Email = "admin@shiwansh.com",
                            Logo = "ehousing.png",
                            Name = "SS E-Housing",
                            RegistrationNumber = "999I",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Housing",
                            BusinessType = "Housing",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7451),
                            Email = "admin@shiwansh.com",
                            Logo = "ehousing.png",
                            Name = "SS E-Housing",
                            RegistrationNumber = "000J",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Onlineshop",
                            BusinessType = "Onlineshop",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7453),
                            Email = "admin@shiwansh.com",
                            Logo = "sszepto.png",
                            Name = "SS Zepto",
                            RegistrationNumber = "K111",
                            Website = "http://www.dotnetinfotech.com/"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Onlineshop",
                            BusinessType = "Onlineshop",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7456),
                            Email = "admin@shiwansh.com",
                            Logo = "sszepto.png",
                            Name = "SS Zepto",
                            RegistrationNumber = "L222",
                            Website = "http://www.dotnetinfotech.com/"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Onlineshop",
                            BusinessType = "Onlineshop",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7458),
                            Email = "admin@shiwansh.com",
                            Logo = "sszepto.png",
                            Name = "SS Zepto",
                            RegistrationNumber = "M333",
                            Website = "http://www.dotnetinfotech.com/"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Education",
                            BusinessType = "Education",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7461),
                            Email = "admin@shiwansh.com",
                            Logo = "ssschool.png",
                            Name = "SS School",
                            RegistrationNumber = "N444",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Education",
                            BusinessType = "Education",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7463),
                            Email = "admin@shiwansh.com",
                            Logo = "ssschool.png",
                            Name = "SS School",
                            RegistrationNumber = "O555",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Education",
                            BusinessType = "Education",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7466),
                            Email = "admin@shiwansh.com",
                            Logo = "ssschool.png",
                            Name = "SS School",
                            RegistrationNumber = "P666",
                            Website = "https://www.shiwansh.com/career.html"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Mohali,Chandigarh",
                            BusinessDescription = "Education",
                            BusinessType = "Education",
                            ContactNo = "6280391882",
                            DateOfIncorporation = new DateTime(2025, 6, 7, 10, 49, 41, 850, DateTimeKind.Local).AddTicks(7469),
                            Email = "homeadmin@shiwansh.com",
                            Logo = "ssdocs.png",
                            Name = "SS Docs",
                            RegistrationNumber = "Q777",
                            Website = "https://www.shiwansh.com/career.html"
                        });
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.HomePageSidebar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HomePageSidebars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = ".Net Core Api Sql",
                            Path = "netcoreapi",
                            TechnologyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = ".Net Core Api PostgreSql",
                            Path = "netcoreapipostgre",
                            TechnologyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = ".Net Core Api Monodb",
                            Path = "netcoreapimongo",
                            TechnologyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dot Net Q/A",
                            Path = "dotnetqa",
                            TechnologyId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "API with MongoDB",
                            Path = "nodeapimongo",
                            TechnologyId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "API with SQL Server",
                            Path = "nodeapisql",
                            TechnologyId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "API with Postgresql",
                            Path = "nodeapipostgre",
                            TechnologyId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Node Js Q/A",
                            Path = "nodeqa",
                            TechnologyId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "CRUD-Static Array",
                            Path = "crudstaticarray",
                            TechnologyId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "CRUD-JSON Server",
                            Path = "crudjsonserver",
                            TechnologyId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "React CRUD with API",
                            Path = "reactcrudwithapi",
                            TechnologyId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "React Js Q/A ",
                            Path = "reactqa",
                            TechnologyId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "VS Code",
                            Path = "vscode",
                            TechnologyId = 9
                        },
                        new
                        {
                            Id = 14,
                            Name = "Visual Studio",
                            Path = "visualstudio",
                            TechnologyId = 9
                        },
                        new
                        {
                            Id = 15,
                            Name = "SQL Server",
                            Path = "sqlserverinstall",
                            TechnologyId = 9
                        },
                        new
                        {
                            Id = 16,
                            Name = "PostgreSql Server",
                            Path = "postgresqlserverinstall",
                            TechnologyId = 9
                        },
                        new
                        {
                            Id = 17,
                            Name = "MongoDB",
                            Path = "mongodbinstall",
                            TechnologyId = 9
                        },
                        new
                        {
                            Id = 18,
                            Name = "Node JS",
                            Path = "nodejs",
                            TechnologyId = 9
                        },
                        new
                        {
                            Id = 19,
                            Name = "SQL Server",
                            Path = "sqlserverdb",
                            TechnologyId = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "PostgreSql Server",
                            Path = "postgresqlserverdb",
                            TechnologyId = 5
                        },
                        new
                        {
                            Id = 21,
                            Name = "MongoDB Server",
                            Path = "mongodbserver",
                            TechnologyId = 5
                        });
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Name = "HealthCareAdmin"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            Name = "JobPortalAdmin"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 6,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 7,
                            Name = "Employer"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 8,
                            Name = "HousingAdmin"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 9,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 10,
                            Name = "Tenant"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 11,
                            Name = "GrosseryAdmin"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 12,
                            Name = "Buyer"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 13,
                            Name = "Seller"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 14,
                            Name = "SchoolAdmin"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 15,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 16,
                            Name = "Student"
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 17,
                            Name = "HomeAdmin"
                        });
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.Sidebar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sidebars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Assign Role",
                            Path = "assignrole",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Role",
                            Path = "role",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Task Manager",
                            Path = "taskmanager",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Doctors",
                            Path = "doctor",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nurses",
                            Path = "nurses",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Patients",
                            Path = "patients",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Reports",
                            Path = "healthcarereports",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Billings",
                            Path = "billings",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rooms",
                            Path = "rooms",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Inventory",
                            Path = "inventory",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Appointments",
                            Path = "doctorappointments",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Patient Records",
                            Path = "patientrecords",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Prescriptions",
                            Path = "doctorprescriptions",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Medical Notes",
                            Path = "medicalnotes",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Test Reports",
                            Path = "testreports",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Appointments",
                            Path = "patientappointments",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 17,
                            Name = "Prescriptions",
                            Path = "patientprescriptions",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "Billing History",
                            Path = "billinghistory",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Reports",
                            Path = "patientreports",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 20,
                            Name = "Messages",
                            Path = "patientmessages",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Country",
                            Path = "country",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "State",
                            Path = "state",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "District",
                            Path = "district",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "Sidebar",
                            Path = "sidebar",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "Technology",
                            Path = "technology",
                            RoleId = 17
                        },
                        new
                        {
                            Id = 26,
                            Name = "Homesidebar",
                            Path = "homesidebar",
                            RoleId = 17
                        });
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.TaskManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskManagers");
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dotnet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NodeJs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ReactJs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NextJs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 6,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Installation"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Migration"
                        });
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "shiwansh@gmail.com",
                            Firstname = "Shiwansh",
                            Lastname = "Kumar",
                            Mobile = "9876543210",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "rajuadmin@gmail.com",
                            Firstname = "Raju",
                            Lastname = "Chauhan",
                            Mobile = "9876543211",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "rajudoctor@gmail.com",
                            Firstname = "Raju",
                            Lastname = "Chauhan",
                            Mobile = "9876543212",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "rajupatient@gmail.com",
                            Firstname = "Raju",
                            Lastname = "Chauhan",
                            Mobile = "9876543213",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "vickyadmin@gmail.com",
                            Firstname = "Vicky",
                            Lastname = "Kumar",
                            Mobile = "9876543214",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "vickyemployee@gmail.com",
                            Firstname = "Vicky",
                            Lastname = "Kumar",
                            Mobile = "9876543215",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 7,
                            Email = "vickyemployer@gmail.com",
                            Firstname = "Vicky",
                            Lastname = "Kumar",
                            Mobile = "9876543216",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 8,
                            Email = "avijitadmin@gmail.com",
                            Firstname = "Avijit",
                            Lastname = "Gorai",
                            Mobile = "9876543217",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 9,
                            Email = "avijitowner@gmail.com",
                            Firstname = "Avijit",
                            Lastname = "Gorai",
                            Mobile = "9876543218",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 10,
                            Email = "avijittenant@gmail.com",
                            Firstname = "Avijit",
                            Lastname = "Gorai",
                            Mobile = "9876543219",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 11,
                            Email = "aniladmin@gmail.com",
                            Firstname = "Anil",
                            Lastname = "Dhakad",
                            Mobile = "9876543200",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 12,
                            Email = "anilbuyer@gmail.com",
                            Firstname = "Anil",
                            Lastname = "Dhakad",
                            Mobile = "9876543220",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 13,
                            Email = "anilseller@gmail.com",
                            Firstname = "Anil",
                            Lastname = "Dhakad",
                            Mobile = "9876543310",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 14,
                            Email = "roshanadmin@gmail.com",
                            Firstname = "Roshan",
                            Lastname = "Kumar",
                            Mobile = "9876543410",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 15,
                            Email = "roshanteacher@gmail.com",
                            Firstname = "Roshan",
                            Lastname = "Kumar",
                            Mobile = "9876543510",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 16,
                            Email = "roshanstudent@gmail.com",
                            Firstname = "Roshan",
                            Lastname = "Kumar",
                            Mobile = "9876543610",
                            Password = "Test@123"
                        },
                        new
                        {
                            Id = 17,
                            Email = "homeadmin@gmail.com",
                            Firstname = "Home",
                            Lastname = "Admin",
                            Mobile = "9876543610",
                            Password = "Test@123"
                        });
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            RoleId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            RoleId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            RoleId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            RoleId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            RoleId = 10,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            RoleId = 11,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            RoleId = 12,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            RoleId = 13,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            RoleId = 14,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            RoleId = 15,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            RoleId = 16,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            RoleId = 17,
                            UserId = 17
                        });
                });

            modelBuilder.Entity("SSHealthCare.Domain.Entities.TaskManager", b =>
                {
                    b.HasOne("SSHealthCare.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SSHealthCare.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
